#!/usr/bin/env bash
# Display information about subdomains.
# shellcheck disable=SC2086
domain="$1"
subdomain="$2"

resultado () {
    if [ "$subdomain" ]
    then
        answer=$(dig "$subdomain"".""$domain" | grep -A1 'ANSWER SECTION:' | tr "\t" "\n" | tail -2 | tr "\n" " ") 
    else
        answer=$(dig "$domain" | grep -A1 'ANSWER SECTION:' | tr "\t" "\n" | tail -2 | tr "\n" " ")
    fi
    echo "$1 $answer" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

if [ "$subdomain" ] 
then
    resultado "$subdomain"
    exit 
fi

if [ "$domain" ]
then 
    resultado www
    resultado lb-01
    resultado web-01
    resultado web-02
fi
