#!/usr/bin/env bash
#Installs NgineX and set up the configuration
sudo apt-get update
sudo apt-get install -y nginx
echo "Holberton School" > /var/www/html/index.nginx-debian.html
sudo service nginx start
