#!/usr/bin/env bash
# Script to install nginx and automatize some functions
apt-get update
apt-get -y upgrade
apt-get -y install nginx
service nginx start
echo "Holberton School" | tee /usr/share/nginx/html/index.html
echo "Holberton School" | tee /etc/nginx/html/index.html
printf %s "server {
     listen      80 default_server;
     listen      [::]:80 default_server;
     root        /etc/nginx/html;
     index       index.html index.htm;
}
" | tee /etc/nginx/sites-available/default
service nginx restart
