#!/usr/bin/env bash
# Configures an Nginx server

apt-get update
apt-get install nginx -y
mkdir /etc/nginx/html
touch /etc/nginx/html/index.html
echo "Holberton School" > /etc/nginx/html/index.html
printf %s "server {
    listen 80 default server;
    listen [::]:80 default_server;
    root /etc/nginx/html;
    index: index.html index.htm;
    location /redirect_me {
           return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4/;
      }

}" > /etc/nginx/sites-available/default
service nginx restart
