#!/usr/bin/env bash
apt-get update
apt-get install -y nginx
echo "Holberton School" > /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" > /var/www/html/404.html

printf %s "server {
    listen 80;
    listen [::]:80 default_server;
    root   /var/www/html/;
    index  index.html index.htm index.nginx-debian.html;
    redirect ^/redirect_me/$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;
    error_page 404 /404.html;
    location /404 {
      root /var/www/html/;
      internal;
    }
}" > /etc/nginx/sites-available/default

service nginx restart
