#!/usr/bin/env bash
# Configures an Nginx server
apt-get update
apt-get -y upgrade
apt-get -y install nginx
service nginx start
echo "Holberton School" | tee /usr/share/nginx/html/index.html
echo "Holberton School" | tee /etc/nginx/html/index.html
echo "Ceci n'est pas une page
" | tee /etc/nginx/html/404.html
printf %s "server {
     listen      80 default_server;
     listen      [::]:80 default_server;
     root        /etc/nginx/html;
     index       index.html index.htm;
     location /redirect_me {
          return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4/;
     }
     error_page 404 /404.html;
     location /404.html {
          root /etc/nginx/html;
          internal;
     }
}
" | tee /etc/nginx/sites-available/default
service nginx restart