#!/usr/bin/env bash
#install load balacer
sudo apt-get -y update
apt-get install -y haproxy=1.6.\*
echo "ENABLED=1" >> /etc/default/haproxy
cp /etc/haproxy/haproxy.cfg /etc/haproxy/original.cfg
echo "
frontend front
    bind *:80
    mode http
    default_backend backend-web

backend backend-web
    mode http
    balance roundrobin
    server 2089-web-01 35.231.45.150:80 check
    server 2089-web-02 34.74.42.82:80 check" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
