#!/usr/bin/env bash
#install load balacer
apt-get update
apt-get install haproxy=1.6.\*
echo "ENABLED=1" >> /etc/default/haproxy
cp /etc/haproxy/haproxy.cfg /etc/haproxy/original.cfg
echo "
frontend front
    bind *:80
    default_backend backend-web

backend backend-web
    balance roundrobin
    server 2089-web-01 35.231.45.150:80 check
    server 2089-web-02 34.74.42.82:80 check

" >> /etc/haproxy/haproxy.cfg

service haproxy restart
