#!/usr/bin/env bash
#install load balacer

sudo apt-get install haproxy -y
echo "ENABLED=1" >> /etc/default/haproxy
mv /etc/haproxy/haproxy.cfg{,.original}
touch /etc/haproxy/haproxy.cfg
printf %s "global
    log 127.0.0.1 local0 notice
    maxconn 2000
    user haproxy
    group haproxy

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    retries 3
    option redispatch
    timeout connect  5000
    timeout client  10000
    timeout server  10000

backend web-backend
    mode http
    stats enable
    stats uri /haproxy?stats
    stats realm Strictly\ Private
    balance roundrobin
    option httpclose
    option forwardfor
    server 2089-web-01 35.231.45.150:80 check
    server 2089-web-02 34.74.42.82:80 check

frontend http
    bind *:80
    mode http
    default_backend web-backend

"" >> /etc/haproxy/haproxy.cfg

service haproxy restart
