#!/usr/bin/env bash
#script performs variety of things

tmp_file=/var/run/holbertonscript.pid
echo $$ > $tmp_file

trap 'echo "Y U no love me?!"' SIGINT
trap 'echo "I hate the kill command"; rm $tmp_file; exit' SIGTERM
trap 'rm $tmp_file; exit' SIGQUIT

while "true"
do
    echo "To infinity and beyond"
    sleep 2
done
