#!/usr/bin/env bash
#Script....

TMP_FILE=/var/run/my_process.pid
case $1 in

"start") 
    ./manage_my_process &
    echo "$!" > $TMP_FILE
    echo "manage_my_process started"
    ;;

"stop")
    echo "manage_my_process stopped"
    rm $TMP_FILE
    kill "$(pgrep -f ./manage_my_process)"
    ;;

"restart")
    kill "$(pgrep -f ./manage_my_process)" > /dev/null
    rm $TMP_FILE
    ./manage_my_process &
    echo "$!" > $TMP_FILE
    echo "manage_my_process restarted"
    ;;

*)
    echo "Usage: manage_my_process {start|stop|restart}"
    ;;
esac
