#!/usr/bin/env bash
#Bash script that groups visitors by IP and HTTP status code, and displays this data.

filename="apache-access.log"
#awk '{a[$1]++} END{for(i in a){print a[i], i, $9}}'  $filename | sort -nr
awk '{ print $1,$9 }' $filename | sort | uniq -c | sort -rn
