#!/usr/bin/env bash
#Bash script that displays Holberton School 10 times, but for the 9th iteration, displays Holberton School and then Hi on a new line.

x=0
while [ $x -lt 10 ]
do
  echo "Holberton School"
  ((x++))
  if [ $x -eq 9 ]
    then
      echo "Hi"
    fi
done
