#!/usr/bin/env bash
# Bash script that loops from 1 to 10 and:
#   displays bad luck for the 4th loop iteration
#   displays good luck for the 8th loop iteration
#   displays Holberton School for the other iterations

x=0
while [ $x -lt 10 ]
do
  if [ $x -eq 3 ]
    then
      echo "Bad luck"
  elif [ $x -eq 7 ]
    then
      echo "Good luck"
  else
    echo "Holberton School"
  fi
  (( x++ ))
done
