#!/usr/bin/env bash
# Configures an Ubuntu server as follows:
#   - localhost resolves to 127.0.0.2
#   - facebook.com resolves to 8.8.8.8

find /etc/hosts -type f -exec sed -i 's/127.0.0.1/127.0.0.2/g' {} \;

echo 8.8.8.8 facebook.com >> /etc/hosts
